<h3>Авторизация</h3>
<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    E-mail *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_email')) ?>" name="client_email" />
<? if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
    <br/>
    Пароль *
    <input type="password" value="<?= $this->escape($this->fromRequest('client_password')) ?>" name="client_password" />
<? if ($this->error['client_password']) { ?>
    <span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
    <br/>
    Запомнить меня
    <input type="checkbox" value="on" name="client_remember" <?php if ($this->inRequest('client_remember')) { ?> checked="checked"<?php } ?> />
    <br/>
    <input type="submit" value="Войти" />
</form>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'registration')) ?>">Регистрация</a>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'recovery')) ?>">Забыли пароль?</a>
