<ul>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client/purchase')) ?>">Ваши заказы</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client/profile')) ?>">Ваши настройки</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client/address')) ?>">Ваши адреса</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client/product')) ?>">Ваши товары</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client/discount')) ?>">Ваша скидка</a></li>
</ul>