<ul>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'purchase')) ?>">Ваши заказы</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'profile')) ?>">Ваши настройки</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'address')) ?>">Ваши адреса</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'product')) ?>">Ваши товары</a></li>
    <li><a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'discount')) ?>">Ваша скидка</a></li>
</ul>