<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru">
	<head>
		<title><?= $this->escape( $this -> meta_title ) ?></title>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<script src="/admin/js/jquery.js" type="text/javascript"></script>
		<script src="/admin/js/interface.js" type="text/javascript"></script>
		<link rel="stylesheet" href="/admin/css/index.css" type="text/css"/>
	</head>
	<body>
		<table class="main">
			<tr>
				<td class="menu">
					<div class="logo">
						<a href="/admin/" title="Айлав"><img src="/admin/image/logo.jpg" alt="Айлав"/></a>
					</div>
<?= $this -> menu ?> 
				</td>
				<td class="content">
<?= $this -> auth ?> 
<?= $this -> content ?> 
				</td>
			</tr>
		</table>
	</body>
</html>
