<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= $this -> meta_title ?></title>
        <meta name="keywords" content="<?= $this -> meta_keywords ?>"/> 
        <meta name="description" content="<?= $this -> meta_description ?>"/> 
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
        <script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <div class="header">
                <div class="left">
                    <div class="logo">
                        <a href="/">Логотип</a>
                    </div>
                    <div class="phone">
<?= Adminko\Module\TextModule::getByTag('phone') ?> 
                    </div>
                    <div class="clear"></div>
                    <div class="callback">
                        <a href="/callback">Обратный звонок</a>
                    </div>
                </div>
                <div class="right">
                    <div class="search">
<?= $this->search ?> Форма поиска
                    </div>
                    <div class="clear"></div>
                    <div class="compare">
<?= $this->compare ?> Сравнение 
                    </div>
                    <div class="cart">
<?= $this->cart ?> Корзина
                    </div>
                    <div class="clear"></div>
                    <div class="purchase">
                        <a href="/purchase">Оформить заказ</a>
                    </div>
                    <div class="clear"></div>
                    <div class="client">
<?= $this->client ?> Регистрация | Войти
                    </div>                
                </div>
            </div>
            <div class="menu">
<?= $this->menu ?> 
            </div>
            <div class="sidebar">
<?= $this->catalogue ?>       
            </div>
            <div class="content">
<?php if ($this->banner) { ?>
<?= $this->banner ?> 
<?php } ?>
<?php if ($this->marker) { ?>
<?= $this->marker ?> 
<?php } ?>
<?php if ($this->brand) { ?>
<?= $this->brand ?> 
<?php } ?>
<?= $this->content ?> 
            </div>
            <div class="footer">
                <div class="subcontact">
<?= Adminko\Module\TextModule::getByTag('subcontact') ?>
                </div>
                <div class="submenu">
<?= $this->submenu ?>
                </div>
                <div class="copyright">
<?= Adminko\Module\TextModule::getByTag('copyright') ?>
                </div>
            </div>            
        </div>            
    </body>
</html>
