<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= $this -> meta_title ?></title>
        <meta name="keywords" content="<?= $this -> meta_keywords ?>"/> 
        <meta name="description" content="<?= $this -> meta_description ?>"/> 
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
    </head>
    <body>
        <header>
            Шапка сайта        
        </header>
        <nav>
            <menu>
                <li>
                    <a href="link1.html">
                        Первая ссылка из блока "nav"
                    </a>
                </li>
                <li>
                    <a href="link2.html">
                        Вторая ссылка из блока "nav"
                    </a>
                </li>
            </menu>
        </nav>
        <aside>
            <menu>
                <li>
                    <a href="link1.html">
                        Первая ссылка из блока "aside"
                    </a>
                </li>
                <li>
                    <a href="link2.html">
                        Вторая ссылка из блока "aside"
                    </a>
                </li>
            </menu>
        </aside>
        <section>
            <article>
                <h1>
                    Заголовок статьи из блока "article"
                </h1>
                <p>
                    Текст абзаца статьи из блока "article"
                </p>
            </article>
        </section>
        <footer>
            <p>
                Содержимое абзаца из блока "footer"
            </p>
        </footer>
    </body>
</html>
