<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title><?= $this -> meta_title ?></title>
        <meta name="keywords" content="<?= $this -> meta_keywords ?>"/> 
        <meta name="description" content="<?= $this -> meta_description ?>"/> 
        <link rel="stylesheet" type="text/css" href="/css/index.css"/>
        <script type="text/javascript" src="/js/jquery-2.1.1.min.js"></script>
        <script type="text/javascript" src="/js/jquery.form.min.js"></script>
        <script type="text/javascript" src="/js/jquery.simplemodal.1.4.4.min.js"></script>
        <script type="text/javascript" src="/js/jquery.selectric.min.js"></script>
        <script type="text/javascript" src="/js/jquery.cycle2.min.js"></script>
        <script type="text/javascript" src="/js/jquery.cycle2.carousel.min.js"></script>
        <script type="text/javascript" src="/js/interface.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <div class="header">
                <div class="left">
                    <div class="logo">
                        <a href="/"></a>
                    </div>
                </div>
                <div class="center">
                    <div class="phone">
<?= Adminko\Module\TextModule::getByTag('phone') ?>
                    </div>
                    <div class="clear"></div>
                    <div class="callback">
                        <input type="button" class="button" value="Заказать звонок" onclick="return callback()" />
                    </div>
                </div>
                <div class="right">
                    <div class="search">
<?= $this->search ?>
                    </div>
                    <div class="clear"></div>
                    <div class="client">
<?= $this->client ?>
                    </div>                
                    <div class="clear"></div>
                    <div class="cart">
<?= $this->cart ?>
                    </div>
                    <div class="clear"></div>
                    <div class="compare">
<?= $this->compare ?>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="main">
                <div class="menu">
<?= $this->menu ?> 
                </div>
                <div class="sidebar">
<?= $this->catalogue ?> 
<?php if ($this->brand) { ?>
<?= $this->brand ?> 
<?php } ?>
                </div>
                <div class="content">
<?php if ($this->teaser) { ?>
<?= $this->teaser ?>
<?php } ?>
<?php if ($this->marker) { ?>
<?= $this->marker ?>
<?php } ?>
<?= $this->content ?>
                </div>
                <div class="footer">
                    <div class="left">
                        <div class="submenu">
<?= $this->submenu ?>
                        </div>
                        <div class="clear"></div>
                        <div class="copyright">
<?= Adminko\Module\TextModule::getByTag('copyright') ?>
                        </div>
                    </div>
                    <div class="right">
                        <div class="subcontact">
<?= Adminko\Module\TextModule::getByTag('subcontact') ?>
                        </div>
                    </div>            
                </div>            
            </div>
        </div>            
    </body>
</html>
