<?php if ($this->catalogue) { ?>
<h1><?= $this->catalogue->getCatalogueTitle() ?></h1>
<?php } ?>

<? foreach ($this->catalogue_list as $catalogue_item) { ?>
<div class="product">
    <div class="image">
        <a href="<?= $catalogue_item->getCatalogueUrl() ?>"><img src="<?= $catalogue_item->getCatalogueImage() ?>/c/150/150"/></a>
    </div>    
    <div class="link">
        <a href="<?= $catalogue_item->getCatalogueUrl() ?>"><?= $catalogue_item->getCatalogueTitle() ?></a>
    </div>    
</div>
<? } ?>

<?php if ($this->catalogue) { ?>
<?= $this->catalogue->getCatalogueDescription() ?>
<?php } ?>
