<?php $pid = uniqid(); ?>
<h1><?= $this->getProductTitle() ?></h1>

<div class="card">
    <div class="picture">
<?php $marker_list = $this->getMarkerList(); ?>
<?php if ($marker_list) { ?>
        <div class="marker">
<?php      foreach ($marker_list as $marker) { ?>
            <img src="<?= $marker->getMarkerImage() ?>" /><br/>
<?php      } ?>
        </div>
<?php } ?>
<?php $picture_list = $this->getPictureList(); ?>
<?php if (count($picture_list) > 1) { ?>
        <div class="picture-wrapper">
            <a href="" id="picture-prev" class="picture-prev"><img src="/image/picture-prev.png"></a>
            <a href="" id="picture-next" class="picture-next"><img src="/image/picture-next.png"></a>
            <div class="picture-slideshow" 
                data-cycle-fx=carousel
                data-cycle-timeout=0
                data-cycle-carousel-visible=1
                data-cycle-next="#picture-next"
                data-cycle-prev="#picture-prev"
                data-cycle-slides="> a"
                >
<?php   foreach ($picture_list as $picture) { ?>
                <a href="<?= $picture->getPictureImage() ?>/c/500/500"> 
                    <img src="<?= $picture->getPictureImage() ?>/c/120/120" />
                </a>
<?php   } ?>
            </div>
        </div>
<?php } else { ?>
        <img src="<?= $this->getProductImage() ?>/c/210/210"/>
<?php } ?>
    </div>
    <div class="property">
        ...
    </div>
    <div class="clear"></div>
    <div class="social">
        ...
    </div>
    <div class="rating">
        ...
    </div>
    <div class="clear"></div>
    <div class="description">
        ...
    </div>
</div>

<br/>

<?php $marker_list = $this->getMarkerList(); ?>
<?php if ($marker_list) { ?>
<?php      foreach ($marker_list as $marker) { ?>
<img src="<?= $marker->getMarkerImage() ?>"><br/>
<?php      } ?>
<?php } ?>

<span class="product_price" pid="<?= $pid ?>"><?= $this->getProductPrice() ?></span><br/>
<?php $package_list = $this->getPackageList(); ?>
<?php if ($package_list) { ?>
<select<?php if (count($package_list) == 1) { ?> disabled="disabled"<?php } ?> class="product_select" pid="<?= $pid ?>">
<?php   foreach ($package_list as $package) { ?>
    <option value="<?= $package->getId() ?>" price="<?= $package->getPackagePrice() ?>"><?= $package->getPackageTitle() ?></option>
<?php   } ?>
</select>
<a href="" class="product_dec" pid="<?= $pid ?>">-</a>
<input type="text" value="1" style="width: 10px" maxlength="1" class="product_value" pid="<?= $pid ?>" />
<a href="" class="product_inc" pid="<?= $pid ?>">+</a>
<a href="" onclick="return buyItem(this);">Купить</a>
<?php } ?>
<?php if (!Adminko\Compare::factory()->in($this->getId())) { ?>
<a href="" onclick="return compareItem(<?= $this->getId() ?>, this);">Сравнить</a>
<?php } ?>
<a href="" onclick="return consultItem(<?= $this->getId() ?>);">Консультация ветеринара</a>

<h4>Рейтинг</h4>
<? $rating = round($this->getProductRating()); ?>
<div class="vote" rating="<?= $rating ?>">
<? for ($i = 1; $i <= 5; $i++) { ?>
    <div class="star<? if ($rating >= $i) { ?> active<? } ?>" id="<?= $this->getId() ?>" mark="<?= $i ?>"></div>
<? } ?>
</div>
<div class="clear"></div>

<h4>Свойства</h4>
<?php foreach ($this->getPropertyList() as $property) { ?>
    <?= $property->getPropertyTitle() ?>:
<?php       if ($property->getPropertyKind() == 'boolean') { ?>
                <?= $property->getPropertyValue() ? 'Да' : 'Нет' ?>
<?php       } else { ?>
                <?= $property->getPropertyValue() ?>
<?php		} ?>
    <?= $property->getPropertyUnit() ?>
    <br/>
<?php } ?>

<h4>Описание</h4>
<?= $this->getProductDescription() ?>

<h4>Отзывы</h4>
<?php if ($this->client) { ?>
<a href="" onclick="return addReview();">Оставить отзыв</a><br/>
<form id="review" method="post" action="<?= Adminko\System::urlFor(array('controller' => 'product', 'action' => 'review', 'id' => $this->getId())) ?>" style="display: none">
    <textarea name="review_text"></textarea>
    <br/>
    <input type="submit" value="Оставить отзыв" />
</form>
<?php } else { ?>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client')) ?>">Авторизуйтесь, чтобы добавить отзыв</a><br/>
<?php } ?>

<?php foreach ($this->getReviewList() as $review) { ?>
<p><b><?= $this->escape($review->getClient()->getClientTitle()) ?></b>, <?= Adminko\date::get($review->getReviewDate()) ?><br/>
<p><?= nl2br($this->escape($review->getReviewText())) ?><p>
<?php } ?>

<h4>Другие товары от <?= $this->getBrand()->getBrandTitle() ?></h4>
<?php foreach ($this->getByBrand() as $product_item) { ?>
<?= Adminko\View::block('module/product/product', $product_item) ?>
<?php } ?>