<?php if ($this->catalogue) { ?>
<h1><?= $this->catalogue->getCatalogueTitle() ?></h1>
<form action="<?= Adminko\System::selfUrl() ?>" method="get">
    <div class="brand">
        <select name="brand">
            <option value="">Выберите бренд</option>
<?php   foreach ($this->catalogue->getBrandList() as $brand) { ?>
            <option value="<?= $brand->getId() ?>"<?php if ($this->inRequest('brand', $brand->getId())) { ?> selected="selected"<?php } ?>><?= $brand->getBrandTitle() ?></option>
<?php   } ?>
        </select>
    </div>

    <div class="sort">
<?php if ($this->sort == 'price') { ?>
        <a href="<?= Adminko\System::requestUrl(array('sort' => 'price', 'order' => $this->order == 'asc' ? 'desc' : 'asc')) ?>">По цене</a>&nbsp;<?php if ($this->order == 'asc') { ?><img src="/image/up.png" /><?php } else { ?><img src="/image/down.png" /><?php } ?></b>
<?php } else { ?>
        <a href="<?= Adminko\System::requestUrl(array('sort' => 'price', 'order' => 'asc')) ?>">По цене</a>
<?php } ?>
        &nbsp;
<?php if ($this->sort == 'name') { ?>
        <a href="<?= Adminko\System::requestUrl(array('sort' => 'name', 'order' => $this->order == 'asc' ? 'desc' : 'asc')) ?>">По названию</a>&nbsp;<?php if ($this->order == 'asc') { ?><img src="/image/up.png" /><?php } else { ?><img src="/image/down.png" /><?php } ?></b>
<?php } else { ?>
        <a href="<?= Adminko\System::requestUrl(array('sort' => 'name', 'order' => 'asc')) ?>">По названию</a>
<?php } ?>
    </div>    
    <div class="clear"></div>
    <div class="filter">
<?php   foreach ($this->catalogue->getPropertyList(true) as $property) { ?>
        <div class="filter_property_container">
            <b><?= $property->getPropertyTitle() ?></b>
        </div>
<?php       if ($property->getPropertyKind() == 'number') { ?>
        <div class="filter_input_container">
            от&nbsp;&nbsp;<input type="text" class="text" name="property[<?= $property->getId() ?>][from]" value="<?= $this->escape($this->fromRequest("property[" . $property->getId() . "][from]")) ?>" style="width: 30px"/>
            &nbsp;
            до&nbsp;&nbsp;<input type="text" class="text" name="property[<?= $property->getId() ?>][to]" value="<?= $this->escape($this->fromRequest("property[" . $property->getId() . "][to]")) ?>" style="width: 30px" />
        </div>
<?php       } elseif ($property->getPropertyKind() == 'boolean') { ?>
        <div class="filter_select_container">
            <select name="property[<?= $property->getId() ?>]" style="width: 53px">
                <option value=""></option>
                <option value="yes"<?php if ($this->inRequest("property[" . $property->getId() . "]", 'yes')) { ?> selected="selected"<?php } ?>>Да</option>
                <option value="no"<?php if ($this->inRequest("property[" . $property->getId() . "]", 'no')) { ?> selected="selected"<?php } ?>>Нет</option>
            </select>
        </div>
<?php       } elseif ($property->getPropertyKind() == 'select') { ?>
        <div class="filter_select_container">
            <select name="property[<?= $property->getId() ?>]" style="width: 100px">
                <option value=""></option>
<?php           foreach ($property->getValueList() as $value) { ?>
                <option value="<?= $value->getId() ?>"<?php if ($this->inRequest("property[" . $property->getId() . "]", $value->getId())) { ?> selected="selected"<?php } ?>><?= $value->getValueTitle() ?></option>
<?php           } ?>
            </select>
        </div>
<?php       } ?>
<?php   } ?>
        <div class="filter_button_container">
            <input type="submit" class="button" value="Применить" />
        </div>
    </div>
</form>
<?php } ?>
<?php if ($this->brand) { ?>
<h3><?= $this->brand->getBrandTitle() ?></h3>
<form action="<?= Adminko\System::selfUrl() ?>" method="get">
    <select name="catalogue" onchange="$(this).parent().submit()">
        <option value="">Выберите раздел</option>
<?php   foreach ($this->brand->getCatalogueList()->getChildren() as $catalogue_group) { ?>
        <optgroup label="<?= $catalogue_group->getCatalogueTitle() ?>">
<?php       foreach ($catalogue_group->getChildren() as $catalogue) { ?>
            <option value="<?= $catalogue->getId() ?>"<?php if ($this->inRequest('catalogue', $catalogue->getId())) { ?> selected="selected"<?php } ?>><?= $catalogue->getCatalogueTitle() ?></option>
<?php       } ?>
        </optgroup>
<?php   } ?>
    </select>
</form>
<?php } ?>

<?php foreach ($this->product_list as $product_item) { ?>
<?= Adminko\View::block('module/product/product', $product_item) ?>
<?php } ?>

<div class="clear"></div>
