<h3><?= $this->marker->getMarkerTitle() ?></h3>

<?php foreach ($this->product_list as $product_item) { ?>
<div style="display: inline-block; width: 200px;">
    <a href="<?= $product_item->getProductUrl() ?>">
        <img src="<?= $product_item->getProductImage() ?>/c/200/200"/>
    </a><br/>
    <a href="<?= $product_item->getProductUrl() ?>"><?= $product_item->getProductTitle() ?></a><br/>
    <?= $product_item->getProductPrice() ?>
</div>
<?php } ?>
<div class="clear"></div>