<?php $pid = uniqid(); ?>
<div style="display: inline-block; width: 200px;">
    <a href="<?= $this->getProductUrl() ?>">
        <img src="<?= $this->getProductImage() ?>/c/200/200"/>
    </a><br/>
<?php $marker_list = $this->getMarkerList(); ?>
<?php if ($marker_list) { ?>
<?php      foreach ($marker_list as $marker) { ?>
    <img src="<?= $marker->getMarkerImage() ?>"><br/>
<?php      } ?>
<?php } ?>
    <a href="<?= $this->getProductUrl() ?>"><?= $this->getProductTitle() ?></a><br/>
    <span class="product_price" pid="<?= $pid ?>"><?= $this->getProductPrice() ?></span><br/>
<?php $package_list = $this->getPackageList(); ?>
<?php if ($package_list) { ?>
    <select<?php if (count($package_list) == 1) { ?> disabled="disabled"<?php } ?> class="product_select" pid="<?= $pid ?>">
<?php   foreach ($package_list as $package) { ?>
        <option value="<?= $package->getId() ?>" price="<?= $package->getPackagePrice() ?>"><?= $package->getPackageTitle() ?></option>
<?php   } ?>
    </select>
    <a href="" class="product_dec" pid="<?= $pid ?>">-</a>
    <input type="text" value="1" style="width: 10px" maxlength="1" class="product_value" pid="<?= $pid ?>" />
    <a href="" class="product_inc" pid="<?= $pid ?>">+</a>
    <a href="" onclick="return buyItem(this);">Купить</a>
<?php } ?>
<?php if (!Adminko\Compare::factory()->in($this->getId())) { ?>
    <a href="" onclick="return compareItem(<?= $this->getId() ?>, this);">Сравнить</a>
<?php } ?>
</div>
