<?= Adminko\View::block('module/client/menu') ?>

<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    <label>Имя <span class="require">*</span></label>
    <input type="text" class="text" value="<?= $this->escape($this->fromRequest('client_title', $this->client->getClientTitle())) ?>" name="client_title" />
<? if ($this->error['client_title']) { ?>
    <span class="error"><?= $this->error['client_title'] ?></span>
<? } ?>
    <br/>
    <label>E-mail <span class="require">*</span></label>
    <input type="text" class="text" value="<?= $this->escape($this->fromRequest('client_email', $this->client->getClientEmail())) ?>" name="client_email" />
<? if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
    <br/>
    <label>Телефон <span class="require">*</span></label>
    <input type="text" class="text" value="<?= $this->escape($this->fromRequest('client_phone', $this->client->getClientPhone())) ?>" name="client_phone" />
<? if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<? } ?>
    <br/>
    <label>Старый пароль</label>
    <input type="password" class="text" value="" name="client_password_old" />
<? if ($this->error['client_password_old']) { ?>
    <span class="error"><?= $this->error['client_password_old'] ?></span>
<? } ?>
    <br/>
    <label>Новый пароль</label>
    <input type="password" class="text" value="" name="client_password" />
<? if ($this->error['client_password']) { ?>
    <span class="error"><?= $this->error['client_password'] ?></span>
<? } ?>
    <br/>
    <label>Подтверждение</label>
    <input type="password" class="text" value="" name="client_password_confirm" />
<? if ($this->error['client_password_confirm']) { ?>
    <span class="error"><?= $this->error['client_password_confirm'] ?></span>
<? } ?>
    <br/>
    <input type="submit" class="button" value="Сохранить" />
</form>