<h1>Результаты сравнения</h1>
<?php if (count($this->product_list)) { ?>
<table class="compare">
    <tr>
        <td rowspan="2" class="title name">
            Товары
        </td>
        <td colspan="<?= count($this->property_list) ?>" class="title">
            Характеристики
        </td>
    </tr>
    <tr>
<?php   foreach ($this->property_list as $property) { ?>
        <td <?php if ($property->getIsEqual()) { ?> class="equal"<?php } ?>>
            <?= $property->getPropertyTitle() ?>
        </td>
<?php   } ?>
    </tr>
<?php foreach ($this->product_list as $product) { ?>
    <tr>
        <td class="name">
            <a href="<?= $product->getProductUrl() ?>"><?= $product->getProductTitle() ?></a>
            &nbsp;&nbsp;
            <a href="<?= Adminko\System::urlFor(array('controller' => 'compare', 'action' => 'delete', 'id' => $product->getId())) ?>" onclick="return confirm( 'Вы уверены, что хотите удалить товар из сравнения?' )"><img src="/image/delete.png" /></a><br/>
            <img src="<?= $product->getProductImage() . '/c/100/100' ?>" alt=""/>
        </td>
<?php       foreach ($this->property_list as $property) { ?>
        <td <?php if ($property->getIsEqual()) { ?> class="equal"<?php } ?>>
<?php                       if ($property->getPropertyKind() == 'boolean') { ?>
                <?= $this->property_compare_list[$property->getId()][$product->getId()] ? 'Да' : 'Нет' ?>
<?php						} else { ?>
                <?= $this->property_compare_list[$property->getId()][$product->getId()] ?>
<?php						} ?>
<?php						if ($this->property_compare_list[$property->getId()][$product->getId()]) { ?>
                <?= $property->getPropertyUnit() ? ' ' . $property->getPropertyUnit() : '' ?>
<?php						} ?>
        </td>
<?php       } ?>
    </tr>
<?php } ?>
</table>
<br/>
<?php if ($this->inRequest('show', 'diff')) { ?>
<a href="<?= Adminko\System::urlFor(array('controller' => 'compare', 'show' => 'all')) ?>">Показать все свойства</a>
<?php } else { ?>
<a href="<?= Adminko\System::urlFor(array('controller' => 'compare', 'show' => 'diff')) ?>">Показать только отличия</a>
<?php } ?>
&nbsp;&nbsp;&nbsp;
<a href="<?= Adminko\System::urlFor(array('controller' => 'compare', 'action' => 'clear')) ?>" onclick="return confirm( 'Вы уверены, что хотите очистить сравнение?' )">Очистить результаты сравнения</a>
<?php } else { ?>
<h2>Нет товаров для сравнения</h2>
<?php } ?>
