<?= Adminko\View::block('module/client/menu') ?>

<h3>Ваша скидка</h3>

Возможные скидки:<br/>
<?php foreach ($this->discount_list as $discount) { ?>
    <?= $discount->getDiscountSum() ?> руб - <?= $discount->getDiscountValue() ?>%<br/>
<?php } ?>

<h4>Сумма ваших заказов: <?= $this->client->getClientSum() ?> руб</h4>

<?php $client_discount = $this->client->getClientDiscount(); ?>
<?php if ($cliPent_discount <> 1) { ?>
<h4>Ваша скидка: <?= 100 - 100 * $client_discount ?>%</h4>
<?php } else { ?>
<h4>Сумма ваших заказов недостаточна, чтобы получить скидку</h4>
<?php } ?>
