<?= Adminko\View::block('module/client/menu') ?>

<div class="purchase selected">
    <p><b>Возможные скидки:</b></p>
    <ul>
<?php foreach ($this->discount_list as $discount) { ?>
        <li><?= $discount->getDiscountSum() ?> руб - <?= $discount->getDiscountValue() ?>%</li>
<?php } ?>
    </ul>
    <p class="total">Сумма ваших заказов: <b><?= number_format($this->client->getClientSum(), 0, ',', ' ') ?> руб</b></p>
<?php $client_discount = $this->client->getClientDiscount(); ?>
<?php if ($cliPent_discount <> 1) { ?>
    <p class="total">Ваша скидка: <b><?= 100 - 100 * $client_discount ?>%</b></p>
<?php } else { ?>
    <p class="total">Сумма ваших заказов недостаточна, чтобы получить скидку.</p>
<?php } ?>
</div>
