<?= Adminko\View::block('module/client/menu') ?>

<h3>Ваши адреса</h3>

<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    Адрес *
    <textarea name="address_title"><?= $this->escape($this->fromRequest('address_title', $this->address->getAddressTitle())) ?></textarea>
<?php if ($this->error['address_title']) { ?>
    <span class="error"><?= $this->error['address_title'] ?></span>
<?php } ?>
<?php if (!$this->address->getAddressDefault()) { ?>
    <br/>
    По умолчанию
    <input type="checkbox" value="on" name="address_default" <?php if ($this->fromRequest('address_default', $this->address->getAddressDefault())) { ?> checked="checked"<?php } ?> />
<?php } ?>
    <br/>
    <input type="submit" value="Сохранить" />
</form>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client/address')) ?>">Вернуться к списку</a>
