<?= Adminko\View::block('module/client/menu') ?>

<?php $address_list = $this->client->getAddressList(); ?>
<?php if ($address_list) { ?>
<?php   foreach ($address_list as $address) { ?>
<div class="purchase <?php if ($address->getAddressDefault()) { ?>selected<?php } ?>">
    <p><b><?= $this->escape($address->getAddressText()) ?></b></p>
    <input type="button" class="button" href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'edit_address', 'id' => $address->getId())) ?>" value="Изменить" />
    <input type="button" class="button" href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'delete_address', 'id' => $address->getId())) ?>" onclick="return confirm('Вы действительно хотите удалить адрес?')" value="Удалить" />
<?php if (!$address->getAddressDefault()) { ?>
    <p class="default"><a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'default_address', 'id' => $address->getId())) ?>">Сделать по умолчанию</a></p>
<?php } else { ?>
    <p class="default">Используется по умолчанию</p>
<?php } ?>
</div>                                                  
<?php   } ?>
<?php } else { ?>
<div class="purchase">
    <p>У вас нет ни одного адреса</p>
</div>
<?php } ?>
<div class="purchase">
    <input type="button" class="button" href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'add_address')) ?>" value="Добавить" />
</div>
