<?= Adminko\View::block('module/client/menu') ?>

<h3>Ваши адреса</h3>
<?php $address_list = $this->client->getAddressList(); ?>
<?php if ($address_list) { ?>
<?php   foreach ($address_list as $address) { ?>
<div style="padding: 10px;<?php if ($address->getAddressDefault()) { ?> background: #f0f0f0;<?php } ?>">
    <b><?= $this->escape($address->getAddressTitle()) ?></b>
    <p><?= $this->escape($address->getAddressText()) ?></p>
    <a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'edit_address', 'id' => $address->getId())) ?>">Изменить</a>
    <a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'delete_address', 'id' => $address->getId())) ?>" onclick="return confirm('Вы действительно хотите удалить адрес?')">Удалить</a>
<?php if (!$address->getAddressDefault()) { ?>
    <br/>
    <a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'default_address', 'id' => $address->getId())) ?>">Сделать по умолчанию</a>
<?php } ?>
</div>                                                  
<?php   } ?>
<?php } else { ?>
<h4>У вас нет ни одного адреса</h4>
<?php } ?>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'add_address')) ?>">Добавить</a>