<p>Спасибо Вам за заказ в интернет-магазине ЗооМафия!</p>

<p>Ваш заказ №<?= $this->purchase->getId() ?>:</p>

<p>
<?php $item_index = 1; ?>
<?php foreach ($this->purchase->getItemList() as $purchase_item) { ?>
<?php   $package = Adminko\Model\Model::factory('package')->get($purchase_item->getItemPackage()); ?>
<?php 	$product = Adminko\Model\Model::factory('product')->get($purchase_item->getItemProduct()); ?>
<?= $item_index ?>. <?= $product->getProductTitle() ?>, <?= $package->getPackageTitle() ?> - <?= $purchase_item->getItemQuantity() ?> шт.<br/>
<?php   $item_index++; ?>
<?php } ?>
</p>

<p>
<?php $delivery = Adminko\Model\Model::factory('delivery')->get($this->purchase->getPurchaseDelivery()) ?>
Способ доставки: <?= $delivery->getDeliveryTitle() ?>
</p>

<p>Общая стоимость заказа: <?= $this->purchase->getPurchaseSum() ?> р.</p>

<p>
Вы указали следующие контактные данные:<br/>
<?= $this->purchase->getPurchasePhone() ?><br/>
<?= $this->purchase->getPurchaseAddress() ?>
</p>

<p>В ближайшее время менеджер свяжется с Вами для уточнения всех деталей.<br>
Если Вы случайно ошиблись при указании адреса или телефона, пожалуйста, перезвоните нам по номерам <?= get_preference('manager_phone') ?>.</p>

<p>Состояние Вашего заказа Вы можете посмотреть, перейдя по ссылке <a href="http://zoo-mafia.ru/client/purchase">http://zoo-mafia.ru/client/purchase</a>.</p>