<?php
    $cart_sum = $this->cart->getSum();
    $purchase_sum = $cart_sum * ($this->client ? $this->client->getClientDiscount() : 1);
    $free_delivery = $purchase_sum >= $this->free_delivery_sum;
?>
<h3>Оформление заказа</h3>
<?php if ($this->cart->getQuantity()) { ?>
<h3>Вы заказали:</h3>
<table border="1">
    <tr>
        <td width="50">
            &nbsp;
        </td>
        <td class="ac">
            <b>Товар</b>
        </td>
        <td width="50">
            <b>Цена</b>
        </td>
        <td width="50">
            <b>Кол-во</b>
        </td>
        <td width="50">
            <b>Стоимость</b>
        </td>
    </tr>
<?php 		foreach ($this->cart->get() as $item) { ?>
<?php 			$package = Adminko\Model\Model::factory('package')->get($item->id); ?>
<?php 			$product = Adminko\Model\Model::factory('product')->get($package->getPackageProduct()); ?>
    <tr>
        <td width="50">
            <img src="<?= $product->getProductImage() ?>/c/50/50" />
        </td>
        <td>
            <?= $product->getProductTitle() ?>, <?= $package->getPackageTitle() ?>
        </td>
        <td width="50">
            <?= $item->price ?>
        </td>
        <td width="50">
            <?= $item->quantity ?>
        </td>
        <td width="50">
            <?= $item->quantity * $item->price ?>
        </td>
    </tr>
<?php 		} ?>
</table>
<h4>Стоимость товаров: <b><?= $cart_sum ?></b> руб</h4>
<?php   if ($purchase_sum < $cart_sum) { ?>
<h4>Стоимость с учетом скидки: <b><?= $purchase_sum ?></b> руб</h4>
<?php } ?>

<?php if ($free_delivery) { ?>
<h4>Доставка бесплатна!</h4>
<?php } ?>

<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    Способ доставки *<br/>
    <select name="purchase_delivery">
<?php foreach ($this->delivery_list as $delivery) { ?>
        <option value="<?= $delivery->getId() ?>"<?php if ($this->inRequest('purchase_delivery', $delivery->getId())) { ?> selected="selected"<?php } ?>>
           <?= $delivery->getDeliveryTitle() ?>
           <?php if (!$free_delivery) { ?>, <?= $delivery->getDeliveryPrice() ?><?php } ?>
      </option>
<?php } ?>
    </select>
<?php if ($this->error['purchase_delivery']) { ?>
    <span class="error"><?= $this->error['purchase_delivery'] ?></span>
<?php } ?>
    <br/>
<?php   if (!$this->client) { ?>
    Имя *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_title')) ?>" name="client_title" />
<?php if ($this->error['client_title']) { ?>
    <span class="error"><?= $this->error['client_title'] ?></span>
<?php } ?>
    <br/>
    E-mail *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_email')) ?>" name="client_email" />
<?php if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<?php } ?>
    <br/>
    Телефон *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_phone')) ?>" name="client_phone" />
<?php if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<?php } ?>
    <br/>
    Адрес доставки *<br/>
    <textarea name="client_address_text"><?= $this->escape($this->fromRequest('client_address')) ?></textarea>
<?php if ($this->error['client_address']) { ?>
    <span class="error"><?= $this->error['client_address'] ?></span>
<?php } ?>
    <br/>
<?php   } else { ?>
    Телефон *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_phone', $this->client->getClientPhone())) ?>" name="client_phone" />
<?php if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<?php } ?>
    <br/>
    Адрес доставки *<br/>
<?php   if ($address_list = $this->client->getAddressList()) { ?>
<?php       foreach ($address_list as $address) { ?>
    <input type="radio" name="client_address"<?php if ($this->inRequest('client_address', $address->getId())) { ?> checked="checked"<?php } ?>/> <?= $this->escape($address->getAddressText()) ?><br/>
<?php       } ?>
    <input type="checkbox" name="client_address_new"<?php if ($this->inRequest('client_address_new')) { ?> checked="checked"<?php } ?>/> Новый адрес<br/>
<?php   } ?>
    <textarea name="client_address_text"><?= $this->escape($this->fromRequest('client_address_text')) ?></textarea>
<?php if ($this->error['client_address']) { ?>
    <span class="error"><?= $this->error['client_address'] ?></span>
<?php } ?>
    <br/>    
<?php   } ?>
    Желаемая дата и время доставки<br/>
    <input type="text" value="<?= $this->escape($this->fromRequest('purchase_request')) ?>" name="purchase_request" />
    <br/>
    Комментарий<br/>
    <textarea name="purchase_comment"><?= $this->escape($this->fromRequest('purchase_comment')) ?></textarea>
    <br/>
    <input type="submit" value="Зарегистрироваться" />
    <a href="/cart">Изменить заказ</a>
</form>
<?php } else { ?>
<h4>Ваша корзина пуста.</h4>
<?php } ?>
