<p>Заказ №<?= $this->purchase->getId() ?></p>

<p>
<?php $item_index = 1; ?>
<?php foreach ($this->purchase->getItemList() as $purchase_item) { ?>
<?php   $package = Adminko\Model\Model::factory('package')->get($purchase_item->getItemPackage()); ?>
<?php 	$product = Adminko\Model\Model::factory('product')->get($purchase_item->getItemProduct()); ?>
<?= $item_index ?>. <?= $product->getProductTitle() ?>, <?= $package->getPackageTitle() ?> - <?= $purchase_item->getItemQuantity() ?> шт.<br/>
<?php   $item_index++; ?>
<?php } ?>
</p>

<p>
<?php $delivery = Adminko\Model\Model::factory('delivery')->get($this->purchase->getPurchaseDelivery()) ?>
Способ доставки: <?= $delivery->getDeliveryTitle() ?>
</p>

<p>Общая стоимость заказа: <?= $this->purchase->getPurchaseSum() ?> р.</p>

<p>
ФИО: <?= $this->client->getClientTitle() ?><br/>
Email: <?= $this->client->getClientEmail() ?><br/>
Телефон: <?= $this->purchase->getPurchasePhone() ?><br/>
Адрес: <?= $this->purchase->getPurchaseAddress() ?><br/>
Дата и время доставки: <?= $this->purchase->getPurchaseRequest() ?><br/>
Комментарий: <?= $this->purchase->getPurchaseComment() ?>
</p>

<p>Перейти к редактированию заказов <a href="http://zoo-mafia.ru/admin/purchase">http://zoo-mafia.ru/admin/purchase</a>.</p>
