<p>Заказ №<?= $this->purchase->get_id() ?></p>

<p>
<? $item_index = 1; ?>
<? foreach ($this->purchase->get_item_list() as $purchase_item) { ?>
<?= $item_index ?>. <?= $purchase_item->get_product()->get_product_title() ?> - <?= $purchase_item->get_product()->get_product_price() ?>р.<br/>
<? 		$item_index++; ?>
<? } ?>
</p>

<p>
<? $package = model::factory('package')->get($this->purchase->get_purchase_package()) ?>
Вид упаковки: <?= $package->get_package_title() ?> - <?= $package->get_package_price() ?>р.<br/>
<? $delivery = model::factory('delivery')->get($this->purchase->get_purchase_delivery()) ?>
Способ доставки: <?= $delivery->get_delivery_title() ?> - <?= $delivery->get_delivery_price() ?>р.
</p>

<p>Общая стоимость заказа: <?= $this->purchase->get_purchase_sum() ?> р.</p>

<p>
ФИО: <?= $this->client->get_client_title() ?><br/>
Email: <?= $this->client->get_client_email() ?><br/>
Телефон: <?= $this->purchase->get_purchase_phone() ?><br/>
Адрес: <?= $this->purchase->get_purchase_address() ?><br/>
Дата и время доставки: <?= $this->purchase->get_purchase_request() ?><br/>
Комментарий: <?= $this->purchase->get_purchase_comment() ?>
</p>