<h3>Восстановление пароля</h3>
<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    E-mail *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_email')) ?>" name="client_email" />
<?php if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<?php } ?>
    <br/>
    <input type="submit" value="Восстановить" />
</form>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client')) ?>">Войти</a>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'registration')) ?>">Регистрация</a>
