			<div class="card">
				<div class="card-inner">
					<div class="order-form-cont order-form">
						<h1>Восстановление пароля</h1>
						<form class="form-horizontal" action="<?= self_url() ?>" method="post">
							<div class="form-group">
								<label for="contact" class="control-label">E-mail<span class="require">*</span>:</label>
								<div class="col-sm-10">
									<input id="client_email" type="text" value="<?= $this->escape($this->from_request('client_email')) ?>" name="client_email" />
								</div>
<? if ($this->error['client_email']) { ?>
								<span class="error"><?= $this->error['client_email'] ?></span>
<? } ?>
							</div>
							<div class="btns-cont">
								<button class="buy-btn big-btn">Отправить</button>
							</div>
						</form>
						<a class="back-to-store" href="<?= url_for(array('controller' => 'client')) ?>">Войти</a>
						<a class="back-to-store" href="<?= url_for(array('controller' => 'client/registration')) ?>">Регистрация</a>
					</div>
				</div>
			</div>
