<h1>Корзина</h1>
<?php if ($this->getQuantity()) { ?>
<form id="cart" method="post" action="<?= Adminko\System::urlFor(array('controller' => 'cart', 'action' => 'save')) ?>">
    <table class="cart">
        <tr>
            <td class="title name">
                Товар
            </td>
            <td class="title price">
                Цена
            </td>
            <td class="title quantity">
                Количество
            </td>
            <td class="title cost">
                Стоимость
            </td>
            <td class="title delete">
                Удалить
            </td>
        </tr>
<?php 		foreach ($this->get() as $item) { ?>
<?php 			$package = Adminko\Model\Model::factory('package')->get($item->id); ?>
<?php 			$product = Adminko\Model\Model::factory('product')->get($package->getPackageProduct()); ?>
        <tr>
            <td class="name">
                <div class="cart_image_container">
                    <img src="<?= $product->getProductImage() ?>/r/100/100"/>
                </div>
                <div class="cart_title_container">
                    <a href="<?= $product->getProductUrl() ?>"><?= $product->getProductTitle() ?>, <?= $package->getPackageTitle() ?></a>
                </div>
            </td>
            <td class="price">
                <?= $item->price ?>
            </td>
            <td class="quantity">
                <input type="hidden" value="<?= $item->price ?>" name="price[<?= $package->getId() ?>]"/>
                <input type="hidden" value="<?= $item->quantity ?>" name="quantity[<?= $package->getId() ?>]"/>
                
                <a href="" class="cart_dec" onclick="return decItem(this)"></a>
                <span class="quantity"><?= $item->quantity ?></span>
                <a href="" class="cart_inc" onclick="return incItem(this)"></a>
            </td>
            <td class="cost">
                <?= $item->quantity * $item->price ?>
            </td>
            <td class="delete">
                <a href="<?= Adminko\System::urlFor(array('controller' => 'cart', 'action' => 'delete', 'id' => $package->getId())) ?>" onclick="return confirm('Вы уверены, что хотите удалить товар?')"><img src="/image/delete.png" /></a>
            </td>
        </tr>
<?php 		} ?>
        <tr>
            <td class="total name">
                &nbsp;
            </td>
            <td class="total price">
                Итого:
            </td>
            <td class="total quantity">
                <?= $this->getQuantity() ?>
            </td>
            <td class="total cost">
                <?= $this->getSum() ?>
            </td>
            <td class="total delete">
                &nbsp;
            </td>
        </tr>
    </table>
</form>
<br/>
<input type="button" class="button" href="javascript: history.back()" value="Продолжить покупки" />
<input type="button" class="button" href="<?= Adminko\System::urlFor(array('controller' => 'cart', 'action' => 'clear')) ?>" confirm="Вы уверены, что хотите очистить корзину?" value="Очистить корзину" />
<input type="button" class="button" href="<?= Adminko\System::urlFor(array('controller' => 'purchase')) ?>" value="Оформить заказ" style="float: right;" />
<?php } else { ?>
<h2>Ваша корзина пуста</h2>
<?php } ?>
