<? if( $this -> count > $this -> by_page ) { ?>
<div class="pages">
<? 		if( $this -> prev_page ) { ?>
    <a href="<?= $this->escape( $this -> prev_page['link'] ) ?>" class="prev-page"></a>
<? 		} ?>
<? 		foreach( $this -> pages as $page ) { ?>
<? 			if( $page['link'] ) { ?>
    <a href="<?= $this->escape( $page['link'] ) ?>"><? if ( $page['number'] ) { ?><?= $page['number'] ?><? } else { ?>&hellip;<? } ?></a>
<? 			} else { ?>
    <b><?= $page['number'] ?></b>
<? 			} ?>
<?		} ?>
<? 		if( $this -> next_page ) { ?>
    <a href="<?= $this->escape( $this -> next_page['link'] ) ?>" class="next-page"></a>
<? 		} ?>
</div>
<? } ?>
