<h3>Регистрация</h3>
<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    Имя *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_title')) ?>" name="client_title" />
<?php if ($this->error['client_title']) { ?>
    <span class="error"><?= $this->error['client_title'] ?></span>
<?php } ?>
    <br/>
    E-mail *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_email')) ?>" name="client_email" />
<?php if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<?php } ?>
    <br/>
    Пароль *
    <input type="password" value="<?= $this->escape($this->fromRequest('client_password')) ?>" name="client_password" />
<?php if ($this->error['client_password']) { ?>
    <span class="error"><?= $this->error['client_password'] ?></span>
<?php } ?>
    <br/>
    Подтверждение *
    <input type="password" value="<?= $this->escape($this->fromRequest('client_password_confirm')) ?>" name="client_password_confirm" />
<?php if ($this->error['client_password_confirm']) { ?>
    <span class="error"><?= $this->error['client_password_confirm'] ?></span>
<?php } ?>
    <br/>
    Телефон *
    <input type="text" value="<?= $this->escape($this->fromRequest('client_phone')) ?>" name="client_phone" />
<?php if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<?php } ?>
    <br/>
    <input type="submit" value="Зарегистрироваться" />
</form>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client')) ?>">Войти</a>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'recovery')) ?>">Забыли пароль?</a>
