<h1>Регистрация</h1>
<form action="<?= Adminko\System::selfUrl() ?>" method="post">
    <label>Имя <span class="require">*</span></label>
    <input type="text" class="text" value="<?= $this->escape($this->fromRequest('client_title')) ?>" name="client_title" />
<?php if ($this->error['client_title']) { ?>
    <span class="error"><?= $this->error['client_title'] ?></span>
<?php } ?>
    <br/>
    <label>E-mail <span class="require">*</span></label>
    <input type="text" class="text" value="<?= $this->escape($this->fromRequest('client_email')) ?>" name="client_email" />
<?php if ($this->error['client_email']) { ?>
    <span class="error"><?= $this->error['client_email'] ?></span>
<?php } ?>
    <br/>
    <label>Пароль <span class="require">*</span></label>
    <input type="password" class="text" value="<?= $this->escape($this->fromRequest('client_password')) ?>" name="client_password" />
<?php if ($this->error['client_password']) { ?>
    <span class="error"><?= $this->error['client_password'] ?></span>
<?php } ?>
    <br/>
    <label>Подтверждение <span class="require">*</span></label>
    <input type="password" class="text" value="<?= $this->escape($this->fromRequest('client_password_confirm')) ?>" name="client_password_confirm" />
<?php if ($this->error['client_password_confirm']) { ?>
    <span class="error"><?= $this->error['client_password_confirm'] ?></span>
<?php } ?>
    <br/>
    <label>Телефон <span class="require">*</span></label>
    <input type="text" class="text" value="<?= $this->escape($this->fromRequest('client_phone')) ?>" name="client_phone" />
<?php if ($this->error['client_phone']) { ?>
    <span class="error"><?= $this->error['client_phone'] ?></span>
<?php } ?>
    <br/>
    <input type="submit" class="button" value="Зарегистрироваться" />
</form>
<br/>
<a href="<?= Adminko\System::urlFor(array('controller' => 'client')) ?>">Войти</a>
&nbsp;&nbsp;&nbsp;
<a href="<?= Adminko\System::urlFor(array('controller' => 'client', 'action' => 'recovery')) ?>">Забыли пароль?</a>
