<script src="/admin/ckeditor/ckeditor.js" type="text/javascript"></script>
<form id="card" action="<?=$this -> form_url?>" method="post" enctype="multipart/form-data" onsubmit="return form_submit( this )">
	<table class="record">
		<tr>
			<td colspan="2" align="left">
				<b><?=$this -> record_title?></b><br/><?=$this -> action_title?>
			</td>
		</tr>
		<tr>
			<td colspan="2" align="right">
				<input type="button" value="Вернуться" class="button" onclick="location.href = '<?=$this -> back_url?>'"/>
			</td>
		</tr>
<?foreach($this -> fields as $name => $field):?>
		<tr>
			<td class="title">
				<?=$field['title']?><?if( $field['require']):?><span class="require">*</span><?endif;?>:
			</td>
			<td class="field">
<?if( $field['type'] === 'boolean' || $field['type'] === 'active' || $field['type'] === 'default'):?>
				<input type="checkbox" name="<?=$name?>" value="1" class="check" errors="<?=join('|', $field['errors'])?>"<?if($field['value']):?> checked="checked"<?endif;?>/>
<?elseif($field['type'] === 'select' || $field['type'] === 'table' || $field['type'] === 'parent'):?>
				<select name="<?=$name?>" class="list" errors="<?=join('|', $field['errors'])?>">
					<option value=""/>
<?foreach($field['values'] as $option):?>
					<option value="<?=$option['value']?>"<?if($option['value'] === $field['value']):?> selected="selected"<?endif;?>><?for($i=0;$i<$option['_depth'];$i++):?>&nbsp;&nbsp;&nbsp;<?endfor;?><?=$option['title']?></option>
<?endforeach;?>
				</select>
<?elseif( $field['type'] === 'date' || $field['type'] === 'datetime'):?>
				<table class="date">
					<tr>
						<td>
							<input type="text" name="<?=$name?>" value="<?=$field['value']?>" class="date" errors="<?=join('|', $field['errors'])?>"/>
						</td>
						<td>
							<a href="" onclick="Calendar.show( document.forms.card['<?=$name?>'], this, '<?if( $field['type'] === 'date'):?>short<?else:?>long<?endif;?>' ); return false">
								<img src="/admin/image/calendar/calendar.gif" alt=""/>
							</a>
						</td>
						<td>
							<a href="" onclick="Calendar.now( document.forms.card['<?=$name?>'], '<?if( $field['type'] === 'date'):?>short<?else:?>long<?endif;?>' ); return false">
								<img src="/admin/image/calendar/check.gif" alt=""/>
							</a>
						</td>
					</tr>
				</table>
<?elseif( $field['type'] === 'image' || $field['type'] === 'file'):?>
				<table class="file">
					<tr>
						<td>
							<input type="file" name="<?=$name?>_file" class="file" size="70%"/>
						</td>
					</tr>
					<tr>
						<td>
							<input type="text" name="<?=$name?>" value="<?=$field['value']?>" class="link" errors="<?=join('|', $field['errors'])?>"/>
						</td>
					</tr>
				</table>
<?elseif( $field['type'] === 'text'):?>
<?if($field['translate']):?>
<?foreach($this -> lang_list as $lang):?>
				<div class="lang"><?=$lang['lang_name']?></div>
				<textarea name="<?=$name?>[<?=$lang['lang_id']?>]" cols="" rows=""<?if(@$field['editor']):?> class="ckeditor"<?endif;?> errors="<?=join('|', $field['errors'])?>"><?=$field['value'][$lang['lang_id']]?></textarea>
				<div class="padding"></div>
<?endforeach;?>
<?else:?>
				<textarea name="<?=$name?>" cols="" rows=""<?if(@$field['editor']):?> class="ckeditor"<?endif;?> errors="<?=join('|', $field['errors'])?>"><?=$field['value']?></textarea>
<?endif;?>
<?else:?>
<?if($field['translate']):?>
<?foreach($this -> lang_list as $lang):?>
				<div class="lang"><?=$lang['lang_name']?></div>
				<input type="text" name="<?=$name?>[<?=$lang['lang_id']?>]" value="<?=$field['value'][$lang['lang_id']]?>" class="text" errors="<?=join('|', $field['errors'])?>"/>
				<div class="padding"></div>
<?endforeach;?>
<?else:?>
				<input type="text" name="<?=$name?>" value="<?=$field['value']?>" class="text" errors="<?=join('|', $field['errors'])?>"/>
<?endif;?>
<?endif;?>
			</td>
		</tr>
<?endforeach;?>
		<tr>
			<td colspan="2">
				<input type="submit" value="Сохранить" class="button"/>
			</td>
		</tr>
	</table>
</form>
<?if($this -> scripts):?>
<script type="text/javascript">
$(function(){
<?foreach($this -> scripts as $function_name => $function_params):?>
	<?=$function_name?>(<?=$function_params?>);
<?endforeach;?>
});
</script>
<?endif;?>
