<b><?=$this -> title?></b><br/><br/>
<?if($this -> mail_count > 0):?>
<div style="border: 1px solid red; background-color: #fff0f0; padding: 10px; margin-bottom: 15px">
	<table class="record">
		<tr>
			<td>
				<b style="color: red">Писем в очереди: <?=$this -> mail_count?></b>
			</td>
			<td style="text-align: right">
				<form action="<?=$this -> cancel_url?>" method="post">
					<input type="submit" value="Отменить" class="button"/>
				</form>
			</td>
		</tr>
	</table>
</div>
<?endif;?>
<script src="/admin/ckeditor/ckeditor.js" type="text/javascript"></script>
<form id="form" action="<?=$this -> form_url?>" method="post" enctype="multipart/form-data" onsubmit="return form_submit( this )">
	<table class="record">
		<tr>
			<td class="title">
				Тема рассылки <span class="require">*</span>:
			</td>
			<td class="field">
				<input type="text" name="subject" value="<?= $this->escape($this -> prev_mail['storage_subject']) ?>" class="text" errors="require"/>
			</td>
		</tr>
		<tr>
			<td class="title">
				От кого (email) <span class="require">*</span>:
			</td>
			<td class="field">
				<input type="text" name="email" value="<?= $this->escape($this -> prev_mail['storage_email']) ?>" class="text" errors="require|email"/>
			</td>
		</tr>
		<tr>
			<td class="title">
				От кого (имя):
			</td>
			<td class="field">
				<input type="text" name="name" value="<?= $this->escape($this -> prev_mail['storage_name']) ?>" class="text"/>
			</td>
		</tr>
		<tr>
			<td class="title">
				Текст рассылки <span class="require">*</span>:
			</td>
			<td class="field">
				<textarea name="body" cols="" rows="" errors="require" class="ckeditor"><?= $this->escape($this -> prev_mail['storage_body']) ?></textarea>
			</td>
		</tr>
		<tr>
			<td class="title">
				Тип рассылки <span class="require">*</span>:
			</td>
			<td class="field">
				<input type="radio" name="type" value="send_to_all"> Всем пользователям<br/>
				<input type="radio" name="type" value="send_to_admin" checked="checked"> Тестовое письмо (только администраторам)<br/>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<input type="submit" value="Отправить" class="button"/>
			</td>
		</tr>
	</table>
</form>
